name: The Bold Report - Development
url: http://localhost:4000
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:title
paginate: 20
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']
timezone: America/Chicago
port: 4000
post:
  extension: md
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
      - _assets/fonts
      - _assets/javascripts
      - _assets/stylesheets
  gzip: false
  cachebust: none
