# General Info
name: The Bold Report
url: https://theboldreport.net
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
timezone: America/Chicago
permalink: /:year/:month/:title/
paginate: 10
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor', '.asset-cache', 'bin']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']

# Where Things Are
plugins_dir:  ./_plugins

# Syntax Highlighting
highlighter: rouge

# Plugins
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

# Server
port: 4000

# Assets
assets:
  compress:
    css: true
    js: true
  digest: true
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets

# Markdown Rendering
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md,mdown

kramdown:
  input: GFM

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: timsmith
