# General Info
name: Development - The Bold Report
url: http://localhost:4000
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
timezone: America/Chicago
permalink: /:title
paginate: 20
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']

# Where Things Are
plugins_dir:  ./_plugins

# Syntax Highlighting
highlighter: rouge

#Plugins
gems:
  - jekyll-assets
  - jekyll-lunr-js-search
  - jekyll-paginate
  - jekyll-sitemap

# Server
port: 4000

# Build Info
assets:
  js_compressor: uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets
post:
  extension: md

# Markdown Rendering
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "no_intra_emphasis", "footnotes", "smart"]
