# General Info
name: The Bold Report
url: http://theboldreport.net
description: 'An exploration of design, development, tech, Geek culture, Apple, and more.'
timezone: America/Chicago
permalink: /:title
paginate: 20
exclude: ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor', '.asset-cache']
lunr_excludes: ['atom.xml', 'atom.articles.xml', 'sitemap.xml']

# Where Things Are
plugins_dir:  ./_plugins

# Syntax Highlighting
highlighter: rouge

# Plugins
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-lunr-js-search

# Server
port: 4000

# Assets
assets:
  compress:
    css: true
    js: true
  digest: true
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/stylesheets

# Markdown Rendering
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "no_intra_emphasis", "footnotes", "smart"]
